[package]
name = "fvi-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fvi-core.workspace = true

bytemuck.workspace = true
tracing.workspace = true
wgpu.workspace = true
winit.workspace = true

[build-dependencies]
wgsl_bindgen.workspace = true

[lints]
workspace = true
