#![doc = include_str!("../README.md")]

pub mod config;
mod context;
mod draw;
mod error;
mod id;
mod types;

#[path = "gfx.g.rs"]
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::allow_attributes_without_reason,
    unsafe_code,
    reason = "generated by wgsl_bindgen"
)]
mod gfx;

pub use error::*;
pub use id::Id;
pub use types::*;

macro_rules! label {
    ($fmt:literal $(, $arg:expr)*) => {
        Some(&format!(
            concat!("fvi:{}.", $fmt),
            ::std::any::type_name::<Self>(),
            $($arg,)*
        ))
    };
}

use label;
