#![doc = include_str!("../README.md")]

mod canvas;
pub mod config;
pub mod context;
mod draw;
mod error;
mod frame;
mod id;
mod raw;
mod unit;

pub use canvas::*;
pub use error::*;
pub use frame::*;
pub use id::*;
pub use unit::*;

#[path = "gfx.g.rs"]
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::allow_attributes_without_reason,
    unsafe_code,
    reason = "generated by wgsl_bindgen"
)]
mod gfx;

macro_rules! label {
    ($fmt:literal $(, $arg:expr)*) => {
        Some(&format!(
            concat!("fvi:{}.", $fmt),
            ::std::any::type_name::<Self>(),
            $($arg,)*
        ))
    };
}

use label;
